### ISSUE TITLE
Baudrate should be variable

### ISSUE THREAD

**Issue by CptChaos** [trizz/dsmr-remote-datalogger#4]
Hello Trizz,

I have an old model meter (DSMR 2.2) so I need to use the 9600 baudrate.
Could you therefor make the baudrate variable? It's now hardcoded to 115200 (see also https://github.com/trizz/dsmr-remote-datalogger/blob/master/dsmr_datalogger_api_client.py#L43).
If I would have any Python knowledge (and got anything to work from what I tried), I would change it myself and create a PR for it, but unfortunatly I don't (or didn't work). I hope / think that solves my issue of the Docker container not starting up (using a Raspberry Pi 3B). Many thanks in advance!

Kind regards,
CptChaos

**Comment by trizz** [comment]
Hi @CptChaos,

No problem, I'll add it in the next release, I guess somewhere this or next week. The issue of not starting the docker container on you Pi 3b possibly relates to #3, which I'll combine with making the baudrate configurable.

**Comment by CptChaos** [comment]
@trizz Thanks in advance and for the fast response!

**Comment by trizz** [comment]
I'm currently updating the script to the [new v4](https://github.com/dennissiemensma/dsmr-reader/blob/v4/dsmr_datalogger/scripts/dsmr_datalogger_api_client.py) version, which has built-in support for setting the baudrate.

I'm currently building and pushing a `develop` tag, I'll close this issue once an official release is tagged.

**Comment by CptChaos** [comment]
Hello @trizz 

Do you want me to test the `develop` tagged image?

Kind regards,
CptChaos

**Comment by trizz** [comment]
@CptChaos That would be great! I've some trouble with the Docker setup that is connected to my P1, so I haven't tested it myself. I should have some time soon to test and release the `develop` version.

**Comment by CptChaos** [comment]
Hello @trizz,

I tried running the container on my Pi (3B+), but it seems to get an error and eventually exits;
```
pi@pi:~/docker/dsmr-remote-datalogger $ docker-compose up
Creating network "dsmr-remote-datalogger_default" with the default driver
Creating dsmr-rdl ... done
Attaching to dsmr-rdl
dsmr-rdl    | INFO:root:[2020-09-18 14:31:19.466796] Starting...
dsmr-rdl    | Traceback (most recent call last):
dsmr-rdl    |   File "./dsmr_datalogger_api_client.py", line 211, in <module>
dsmr-rdl    |     main()
dsmr-rdl    |   File "./dsmr_datalogger_api_client.py", line 154, in main
dsmr-rdl    |     DATALOGGER_INPUT_METHOD = decouple.config('DATALOGGER_INPUT_METHOD')
dsmr-rdl    |   File "/usr/local/lib/python3.8/site-packages/decouple.py", line 199, in __call__
dsmr-rdl    |     return self.config(*args, **kwargs)
dsmr-rdl    |   File "/usr/local/lib/python3.8/site-packages/decouple.py", line 83, in __call__
dsmr-rdl    |     return self.get(*args, **kwargs)
dsmr-rdl    |   File "/usr/local/lib/python3.8/site-packages/decouple.py", line 68, in get
dsmr-rdl    |     raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
dsmr-rdl    | decouple.UndefinedValueError: DATALOGGER_INPUT_METHOD not found. Declare it as envvar or define a default value.
```

I get that I should set `INPUT_METHOD`, but I don't know what the available values are. I hope I am not doing something stupid, hahaha! :P

**Comment by svanrossem** [comment]
I think you can close this issue. See the updated https://github.com/trizz/dsmr-remote-datalogger/tree/develop#usage.

**Comment by CptChaos** [comment]
Yep, thanks for the update!
